---
pipes:
  - name: testPipe
    filters:
      - addAsteriks
      - addDashes
      - removeVovel
  - name: testPipe2
    filters:
      - removeVovel
      - addDashes
      - addAsteriks
  - name: testPipe3
    filters:
      - addDashes
      - addDashes
      - addDashes
